inherit_from:
  - .rubocop_airbnb.yml

require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Exclude:
    - 'app/models/account.rb'
    - 'app/controllers/api/v1/accounts_controller.rb'